<?php
	//require_once("../../common/telegram.lib.php");

	function genSentence($part){
		global $db;
		$statement = $db->prepare("SELECT id, turtle.part, prefix, content FROM turtle JOIN turtle_prefix on turtle.part = turtle_prefix.part WHERE turtle.part=?");
		$statement->bindValue(1, $part);
		$statement->execute();
		$contents = array();
		while ($result = $statement->fetch()){
			if (!isset($prefix))
				$prefix = $result["prefix"];
			array_push($contents, $result["content"]);
		}
		return $prefix.$contents[rand(0, count($contents)-1)]."\n";
	}	

	if (!timerlock("turtle")){
		$content = "";
		for ($i = 1; $i <= 9; $i++)
			$content .= genSentence($i);

		$content .= "\nGenerated by CUHK Bot Turtle Back Generator at ".date("Y-m-d H:i:s");
		sendMessage($content);
	}

?>